version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./.docker/php
            dockerfile: Dockerfile
        image: example
        hostname: app
        container_name: example_app
        restart: unless-stopped
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            PHP_IDE_CONFIG: "serverName=localhost"
            XDEBUG_CONFIG: "idekey=PHPSTORM"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - bubble

    nginx:
        build: .docker/nginx
        hostname: nginx
        container_name: example_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/app
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - bubble
        depends_on:
            - app

    redis:
        image: redis
        hostname: redis
        container_name: example_redis
        ports:
            - "6379:6379"
        volumes:
            - ./.docker/redisdata:/data
        networks:
            - bubble

    prometheus:
        image: prom/prometheus:latest
        hostname: prometheus
        container_name: example_prometheus
        volumes:
            - ./.docker/prometheus/prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.enable-lifecycle'
        ports:
            - "9092:9090"
        depends_on:
            -   app
        networks:
            - bubble

    grafana:
        container_name: grafana
        hostname: grafana
        image: grafana/grafana:latest
        ports:
            - '3001:3000'
        depends_on:
            - prometheus
        networks:
            - bubble
networks:
    bubble:
        external: true
        driver: bridge

volumes:
    mysql: {}
    nginx: {}
    prometheus_data: {}
