global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: app
    scrape_interval: 5s
    static_configs:
      - targets:
          - nginx:80


#scrape_configs:
#  - job_name: redis
#    scrape_interval: 5s
#    metrics_path: "/metrics"
#    static_configs:
#      - targets:
#          - redis:6379

#  - job_name: prometheus
#    metrics_path: "/metrics"
#    scrape_interval: 5s
#    static_configs:
#      - targets:
#          - prometheus:9090
#
#  - job_name: app
#    scrape_interval: 5s
#    static_configs:
#      - targets:
#          - nginx:80
